### ISSUE TITLE
“Report” function should work as in previous software

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#11]
“Report” function should work as in previous software. After selecting files, it should allow user to preview the report and allow user to print or save as PDF or share the report.
-Khai Ta

Edit file now automatically navigates back to dashboard after saving.
-William G. Rothrock

Last entry was for bug 74 not bug 71.
-William G. Rothrock

Preview is available for print selection, but Android lacks the ability to render a PDF inside of the web view without a 3rd party application, which would add extra steps and still require the user to hit the back button and then select the print or email option.
-William G. Rothrock

Maxton to review. Android OS does not allow PDF render within app. Would be a significant change to implement workaround
-William G. Rothrock

**Comment by maxtonengineer** [comment]
Maxton has reviewed with RDM, android does not easily allow preview function before generating pdf for email. Users wanting this feature may use iOS
