### ISSUE TITLE
Bluetooth does not reconnect and transmit data after finishing run with a connection problem 

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#13]
HW Rev-C
Firmware v1.0.6
RDM App v1.0.9

During testing, we created a loss of signal by triggering a run from the machine room, with the tablet remaining in the machine room, on a 9 story building. Upon completing the run (a down run), and bringing the car back up, the tablet did not connect back to the node and complete the run. We brought them to within a few feet from each other, and the tablet did not reconnect and receive the data from the node.

We believe this was functioning on the previous Android application written by Chris Simpson. Will confirm previous behavior and intended functionality.
-David Gabriel

**Comment by maxtonengineer** [comment]
On testing on 10/22/2018, we experienced two BT disconnections on runs with node 3 but at the end of the these two runs, the BT reconnected and data was successfully transmitted. We need to keep a watch on this issue throughout the duration of our testing and note any such occurrences.

**Comment by rdminfinity** [comment]
Updated timers to run for 5 minutes per discussion with David in v1.0.12
