### ISSUE TITLE
Bug 61 - OSV mode does not work if previous runs set in Hydro mode #5

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#16]
Make OSV mode has its own entity and independent with other modes. SafeTach2 needs to be set to “Traction” and a run is completed then when switching to OSV, it will display the proper readings. It should display "OSV" on top of “Dashboard” screen.
-Khai Ta

This does not appear to be how any of the original source code handles OSV. There are 3 separate values for the run type flag passed to the node when a run is being recorded, uniquely identifying it as a Hydro, Traction, or OSV run. When the node reports back all of the data captured on the run, it includes a value from which the run type is parsed back out, defining that run again as one of those 3 types.
-William G. Rothrock

Maxton to clarify desired behavior in more detail to RDM
-William G. Rothrock

Desired behavior:

    Set Client software to "OSV/Governor" from either “Traction” or “Hydro” mode.
    Tap Menu then “New Run”.
    Make a down run to activate the OSV. Few seconds after car stopped, the software should display values for down high speed and other data on Dashboard screen whether the elevator reached stabilized down high speed or not. “OSV/Gov” should be displayed on the top area where "Traction" or "Hydro" is displayed.
    See picture "OSV mode pic1.png".

Changes to graphic on "Settings" screen: Replace the word "OSV" by "OSV/Governor".
See picture "OSV mode pic2.png".
-Khai Ta

v1.0.7

    Unable to repeat this bug. We conducted multiple tests changing the settings to OSV after both traction and hydro runs, triggered new runs, and generated uniform results. May need examples of issue or walk through.

    Changed run type in title bar and button to say OSV/Gov
    -RDM

OSV Mode appears to be working in 1.0.8. Displays level speed in test, but no high speed. I cannot reproduce bug in 1.0.8 on iPad mini.
-David Gabriel

Does not display "OSV" at the top of the run, but still displays previous run of either "hydro" or "traction" at the top. Text was changed on button, but not on title bar.

Does not display level speed if previous mode is traction.

Chris Simpson did not finish development of OSV mode.
-David Gabriel

We need to schedule a call/meeting to walk through this when possible. Will follow up with email to schedule.
-RDM

![image](https://user-images.githubusercontent.com/41277519/47238147-11ae7080-d396-11e8-998b-c4f749ebb1d1.png)

![image](https://user-images.githubusercontent.com/41277519/47238156-1a06ab80-d396-11e8-81d3-7d5f8e488eaf.png)

**Comment by maxtonengineer** [comment]
Maxton to confirm OSV mode now has correct state machine function. Currently OSV/GOV reports on levelling speed and not high speed values. Will need to report high speed value similar to traction, where high speed reports value and level speed is greyed out.

**Comment by maxtonengineer** [comment]
Value currently reported in stop rate of OSV / GOV mode will be displayed as "DECELERATION" and stop will be replaced with Maxton logo.
