### ISSUE TITLE
Hydro Run reporting in excess of 3000 fpm, during 100 fpm runs

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#19]
Hardware Revision C
Firmware Revision (node) v1.0.6
Software Revision (mobile application) v1.0.9

Hydro Run testing, approximately 100 fpm, SafeTach 2 reports in excess of 3000 fpm high speed results in the up direction. Issue does not present during down direction runs in this instance. Data recorded 9-18-18, see attachment
-David Gabriel

![image](https://user-images.githubusercontent.com/41277519/47241917-2bee4b80-d3a2-11e8-89c6-0522783a922f.png)

**Comment by maxtonengineer** [comment]
Issue has been resolved in V1.0.10 (Android) V1.0.11 (iOS)
