### ISSUE TITLE
iOS 1.0.11 Graphing does not display any graphs

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#24]
The graphs do not populate on the screen in iOS app version 1.0.11

**Steps to Reproduce**
1.Open app on iOS v1.0.11
2. Connect to node in settings menu of app.
3. Trigger and complete run measurement
4. Select "Graphing" from main menu.
5 All graphs displayed are not populated with data. All 

**Expected behavior**
Graph should populate with data

**Screenshots**
![img_0073 1](https://user-images.githubusercontent.com/41277519/47449785-5a8c6d80-d778-11e8-9871-3b6cf3b027e6.PNG)
![img_0072 1](https://user-images.githubusercontent.com/41277519/47449794-5f512180-d778-11e8-8ded-b24754a3b6d9.PNG)
![img_0071 1](https://user-images.githubusercontent.com/41277519/47449796-6415d580-d778-11e8-9e60-6432b20cc887.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad mini
 - OS: iOS
 - Browser n/a
 - Version v1.0.11

**Additional context**

**Comment by rdminfinity** [comment]
Requested CSV sample data from Maxton. David to generate and send.

**Comment by maxtonengineer** [comment]
Reviewed onsite. Graph displayed
