### ISSUE TITLE
iOS version of RDM app does not display the node's BT MAC address

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#26]
**Description**
On the iOS version of the RDM app, the node's Bluetooth MAC address is never displayed. Instead, in the connection menu, it displays a long string of characters that is different from both the node's serial number and the node's Bluetooth MAC address. The same is true for every Bluetooth capable device detected by the app. it would display a long string of characters rather than the device's Bluetooth MAC address.

**To Reproduce**
Go into the connect menu of the app and do a scan for nearby Bluetooth devices. You will see that all detected devices have a long string of characters displayed next to their names rather than their actual Bluetooh MAC addresses.

**Expected behavior**
We want the iOS version of the RDM app to display the device's Bluetooth address next to its name in the connect menu like the Android version of the app currently does.

**Screenshots**
![image1](https://user-images.githubusercontent.com/13562720/47666929-f8f64580-db61-11e8-8889-38656ff3b4e4.jpeg)

**Comment by rdminfinity** [comment]
IOS does not allow for direct access to the MAC address per the Apple privacy guidelines. Discussed with David and we will leave as is for now.
