### ISSUE TITLE
Continuously attempt to reconnect to node if connection is lost

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#27]
**Description of Feature Request**
Currently on both the Android and iOS versions of the RDM app, whenever Bluetooth connection is temporarily lost, a few seconds, it would automatically reconnect. However, on occasion when   connection is lost for a minute or more, neither versions of the app consistently reconnects. That is, after losing Bluetooth connection for over a minute, the app and node does not always reconnect. 

**Desired Solution**
Bluetooth disconnects with SafeTach 2 can be a common occurrence in the field as often times, the mobile device running the app and the node may not have direct line of sight with one another, thus greatly reducing the effective range of Bluetooth. Also, an elevator mechanic may be working on a traction elevator in a skyscraper, which will cause the Bluetooth to lose signal if a call takes the node beyond 100m from the mobile device. It is for these reasons that we want the app to be able to reconnect the node through out the duration the node is on, up to 30 minutes, even as it is hopping broadcast channels.

**Comment by rdminfinity** [comment]
Related to issue #13 . Both updated in v1.0.12
