### ISSUE TITLE
When starting a run without BTLE connection, redirect user to settings/connection as necessary

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#29]
**Users without experience may have trouble finding the correct setting to produce BTLE connection**
When installing the app, it asks for permissions unrelated to BTLE, but these permissions do affect Bluetooth connection. Some users will not know where to initiate Bluetooth connection 

**Describe the solution you'd like**
If permissions are not enabled on the device, prompt user and provide a button which will redirect to the settings menu so the user can enable settings. If the device is not connected, redirect users with a button to the connect device screen. 

**Describe alternatives you've considered**
We could leave device as is.

**Comment by davidgabriel42** [comment]
Permissions not enabled, preventing BTLE connection. Does not prompt to enable permissions. 

![image](https://user-images.githubusercontent.com/41277519/47939144-88259500-dea3-11e8-9ba4-d990efaddd89.png)

**Comment by rdminfinity** [comment]
There could be an issue doing this on IOS. Notes from RDM developer:

showBluetoothSettings is not available on iOS. Plugins like cordova-diagonostic-plugin and the Ionic Native Diagnostic plugin have APIs to open Bluetooth and other settings, but will often get apps rejected by Apple.

How would you like us to proceed?

**Comment by rdminfinity** [comment]
Updated in v1.0.13 per our conversation on 11/7/18.
