### ISSUE TITLE
Incorporate All Help Screen Pages from Chris' App into RDM's App and Have it Pop Up on Launch

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#30]
**Description of Desired Feature**
RDM's app should have the same number of help screen pages as Chris' app. The values displayed in the help screen pages should be adjusted accordingly to fit the last round of changes made to the app. That is, the high and leveling speed values should be rounded to the nearest feet per minute (fpm) and the stop acceleration hidden. In addition to this, when the app is launched, all of the help screen pages should pop up on the screen (similar to a ReadMe display) with an optional check box that if checked, will stop the help screen pages from popping up on subsequent launches.

**Comment by rdminfinity** [comment]
Updated for next release (v1..0.13)
