### ISSUE TITLE
Remove Stop Acceleration Value in Report File

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#31]
**Description**
The stop acceleration value should be removed in the pdf report file being generated as we are not displaying it in the dashboard.

**Attachments**
[safetach2.pdf](https://github.com/maxtonengineer/SafeTach-2-Project/files/2540461/safetach2.pdf)

**Comment by rdminfinity** [comment]
Updated for next release (v1..0.13)
