### ISSUE TITLE
Remove or Set Level Speed to 0 on PDF Reports when on Traction and OSV/Gov Mode

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#32]
**Description**
Remove or Set Level Speed to 0 on PDF Reports when on Traction and OSV/Gov Mode

**Attachments**
[safetach2.pdf](https://github.com/maxtonengineer/SafeTach-2-Project/files/2540508/safetach2.pdf)

**Comment by rdminfinity** [comment]
Updated for next release (v1..0.13)
