### ISSUE TITLE
Have the Back Button on Android Devices go to the Dashboard when Pressed

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#33]
**Description of Feature**
On Android devices, the Back Button takes the user out of the SafeTach 2 app and to the home screen of the device when pressed. In the process, it also disconnects the device from the SafeTach 2 node. We want this changed so that when pressed by the user, the screen automatically returns to the Dashboard of the app.

**Comment by rdminfinity** [comment]
We can change this again. The current functionality was added after the initial meeting and rollout of the app. Can we confirm the functionality needed before we make programming changes?

**Comment by rdminfinity** [comment]
Updated in v1.0.13
