### ISSUE TITLE
OSV Mode Reporting Changes

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#34]
**OSV MODE REPORTS LEVEL SPEED VALUE, NO HIGH SPEED, VALUE IS WRONG**
OSV Mode is not reporting the maximum speed during OSV run, but instead reports a level speed. OSV Mode shouldn't have a level speed. Decel is not reporting. Graphs look good and contain accurate responsive ride data for all errant runs encountered. 

**To Reproduce**
When triggering an OSV mode run, on stand 3, select new run and run car down in high speed to trip OSV. 

**Expected behavior**
OSV Mode runs should report maximum speed during run, and no level speed. The Decel should report the deceleration value, which is is not currently. 

Because the graphs plot well ** it should be easy to detect the minimum value in the graphing data and report this as the high speed.**

**Screenshots**
![img_0075 1](https://user-images.githubusercontent.com/41277519/47933254-4db2fc80-de91-11e8-8837-de5184ca0c26.PNG)

![img_0076 1](https://user-images.githubusercontent.com/41277519/47933239-4390fe00-de91-11e8-8c82-4361c9232e6a.PNG)

![img_0077 1](https://user-images.githubusercontent.com/41277519/47933222-3542e200-de91-11e8-9857-7a6a9330e1cf.PNG)

**Smartphone (please complete the following information):**
 - Device: iPad mini
- OS: iOS12.0.1
 - Version 1.0.12

**Additional context**
OSV is a device which halts car movement in the event of a pipe rupture in a situation like an earthquake. This means an OSV run is a down run that stops abruptly, without level speed.

**Comment by davidgabriel42** [comment]
![image](https://user-images.githubusercontent.com/41277519/47938488-74792f00-dea1-11e8-8f5f-e23c0040acae.png)

Graph showing high speed value circled in red. Doing a min search function on the graphed values will produce a proper high speed.

What was previously stop rate should be shown as decel.

**Comment by rdminfinity** [comment]
Updated for next release (v1..0.13)
