### ISSUE TITLE
During Report Generation- screen layout error blocks half of screen.

### ISSUE THREAD

**Issue by maxtonengineer** [maxtonengineer/SafeTach-2-Project#35]
**Report Generation Causes Screen to be blocked**
While generating a report, selecting multiple runs, screen is blocked out preventing user from seeing the screen. 

**To Reproduce**
1. Go to Report
2. Click on runs
3. See error

**Expected behavior**
Screen should display and be readable. 

**Screenshots**

![image-1](https://user-images.githubusercontent.com/30448760/47945653-b06fbc80-dec0-11e8-962c-97639c34dd7e.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: iOS
*Additional context**

**Comment by maxtonengineer** [comment]
Was observed on Bill's device, with font size increased

**Comment by maxtonengineer** [comment]
The issue is directly related to the "Display and Brightness" setting "Display Zoom"

**Comment by rdminfinity** [comment]
Updated in v1.0.13
