### ISSUE TITLE
Bluetooth Issue

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#54]
**Bluetooth Issue**
Bluetooth connection sometimes drops out, reconnects and shows packet transfer exceeding 100%. Node then hangs and is unresponsive to power cycling until battery is disconnected. 

**To Reproduce**
1. Running on stand 4 and later on stand 5, we observed the issue 3 times in less than 2.5 hours. After each time, the power button was unresponsive.

**Expected behavior**
In worst cast scenario, power cycling should be functional. Bluetooth should not cause node to hang. 

**Smartphone (please complete the following information):**
 Android ST2 v 1.0.15

**Comment by rdminfinity** [comment]
Resubmitted v1.013 and v1.0.14 for regression testing by Maxton.
