### ISSUE TITLE
Splash Screen Should Have Maxton Logo

### ISSUE THREAD

**Issue by mmcheng93** [maxtonengineer/SafeTach-2-Project#55]
**Description of Issue**
The splash screen in version _1.0.15_ of the app does not have the Maxton Logo. 

**Expected Layout**
We want to have the Maxton Logo on the splash screen in addition to the SafeTach 2 label.

![screenshot_20181121-132213 1](https://user-images.githubusercontent.com/13562720/48869313-a63f3080-ed91-11e8-933a-8ac707dca9ba.png)

**Comment by maxtonengineer** [comment]
Maxton Logo is on the splash screen as of v17.
