### ISSUE TITLE
Weird Spike in Acceleration at the Beginning of Down Runs 

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#6]
During testing using the latest version of Chris' app with the overflow and z static calibration corrections implemented, we noticed an issue that would occur on all 6 of the nodes we currently have. The issue that occurred was that on down runs, a spike in the acceleration (positive direction) would occur in within 0.5 seconds of starting the run. This spike throws off the high speed calculation, and we end up with high speed values that are typically between 30 to 60 fpm off of the test stand values. We believe that this issue may be correlated to the Bluetooth signal strength as it seems to only occur when the tablets running the app are not within line of sight of SafeTach 2 nodes or are fairly far away (beyond 10 feet). When they are within line of sight and are in close proximity to the nodes (less than 10 feet away), we did not run into this issue. In total, we tested the nodes with the new version of Chris' app more than 200 times, and had this issue pop up about 10 times; all on down runs. Again, this may be correlated to Bluetooth signal strength, but we have no conclusive evidence to back up this claim. We will wait until RDM releases the latest version of the app and test to see if this issue occurs before determining a cause. Please see the images below for examples of what the GUI on Chris' app displays whenever this issue occurs during a run.
-Michael Cheng

**Comment by davidgabriel42** [comment]
![image](https://user-images.githubusercontent.com/41277519/47232100-a65ba300-d383-11e8-9dc3-a9f05c018c20.png)

![image](https://user-images.githubusercontent.com/41277519/47232110-aeb3de00-d383-11e8-84c2-9af3194abb8d.png)

![image](https://user-images.githubusercontent.com/41277519/47232114-b2476500-d383-11e8-9512-03f7c290145b.png)

![image](https://user-images.githubusercontent.com/41277519/47232134-b96e7300-d383-11e8-9cc9-ad989ca61f94.png)

![image](https://user-images.githubusercontent.com/41277519/47232139-bd01fa00-d383-11e8-84b6-0929e13fa6e0.png)

![image](https://user-images.githubusercontent.com/41277519/47232147-c0958100-d383-11e8-9c0d-82fb86903478.png)

![image](https://user-images.githubusercontent.com/41277519/47232153-c4290800-d383-11e8-8d32-11fd12aac9ea.png)

![image](https://user-images.githubusercontent.com/41277519/47232163-ca1ee900-d383-11e8-8c3a-19e65770c86d.png)

![image](https://user-images.githubusercontent.com/41277519/47232169-cee39d00-d383-11e8-851c-17dc1e10d6a5.png)

**Comment by maxtonengineer** [comment]
Resolved node side
