### ISSUE TITLE
Too many decimal figures on High Speed, Level Speed, Run Time, Jerk and maybe others

### ISSUE THREAD

**Issue by davidgabriel42** [maxtonengineer/SafeTach-2-Project#9]
There are too many non significant figures (decimal places) in the output display of the Speeds.
-David Gabriel

hydro run 1
![image](https://user-images.githubusercontent.com/41277519/47232766-73b2aa00-d385-11e8-9c1a-100d408537ee.png)

slow speed run 1
![image](https://user-images.githubusercontent.com/41277519/47232784-862ce380-d385-11e8-9b01-1d1e201d0ff1.png)

decimal place requirements
![image](https://user-images.githubusercontent.com/41277519/47232795-904ee200-d385-11e8-96e4-1b7122ed790a.png)

![image](https://user-images.githubusercontent.com/41277519/47232805-9644c300-d385-11e8-84d3-d6c72155862c.png)

**Comment by davidgabriel42** [comment]
We really should standardize on the correct number of sig figs to use. I doubt our instruments are accurate up to thousandths of a foot or cm.
- Michael Cheng (copied from previous bug)

**Comment by rdminfinity** [comment]
Updated in v1.0.12
